### ISSUE TITLE
removing a partition inside super.img ?

### ISSUE THREAD

**Issue by LeOS-GSI** [ChromiumOS-Guy/SuperPatcherGSI#4]
Will it be possible to remove a partition in super.img ? That's my layout:
option number 0 system.img size of (1025503232) bytes
option number 1 product.img size of (717328384) bytes
option number 2 vendor.img size of (286715904) bytes
and to get more free space i need to remove the product.img.
Do you know how I can do ? Or add a new option for removing partition ?

**Comment by ChromiumOS-Guy** [comment]
I will add a new option at Saturday my time until then when it asks you to choose an partition to replace just go the directory where the script is running (don't close the script) you will see a folder named tmp delete the desired partition from there (don't replace a partition before doing this because then the script will calculate the nonexistent partition which may cause errors) 
edit:
also don't replace a deleted partition as this will 100% crash the script because of how the script does things (I'll probably also implement a bunch of fail safes but until then the script will just crash)

**Comment by LeOS-GSI** [comment]
cool. Next time I will check it. For your information, the new generated super.img is working fine on my Smartwatch. Now I have a full degoogled Android 13 Smartwatch 🙂
________________________________
Von: ChromiumOS-Guy ***@***.***>
Gesendet: Dienstag, 13. Juni 2023 13:27
An: ChromiumOS-Guy/SuperPatcherGSI ***@***.***>
Cc: harvey186 ***@***.***>; Author ***@***.***>
Betreff: Re: [ChromiumOS-Guy/SuperPatcherGSI] removing a partition inside super.img ? (Issue #4)


I will add a new option at Saturday my time until then when it asks you to choose an partition to replace just go the directory where the script is running (don't close the script) you will see a folder named tmp delete the desired partition from there (don't replace a partition before doing this because then the script will calculate the nonexistent partition which may cause errors)

**Comment by ChromiumOS-Guy** [comment]
cool :slightly_smiling_face: , I hope it will continue working without crashing or something

**Comment by LeOS-GSI** [comment]
one OffTopic question: Are you building ChromiumOS ? I'm very interested in building Chromium. But I'm always stuck at the point where you will need a google account. I don't have one.

**Comment by ChromiumOS-Guy** [comment]
sorry I builded ChromiumOS way back like 5y ago because I wanted to shove Widevine DRM content on ChromiumOS so I can watch my Netflix on my RockPro64 SBC media center, most of my knowledge involves compiling ChromiumOS  for arm64 specifically for the Rockchip RK3399 architecture for the RockPro64 and stealing the Widevine from ChromeOS recovery binaries
edit:
this name kinda stuck from back then on my social platforms so I just kinda use it

**Comment by ChromiumOS-Guy** [comment]
also OffTopic question
can you give me some pointers on how to make a GSI (the android docs are good but experience is better)

**Comment by LeOS-GSI** [comment]
Sure, building GSI is easy. Use Andy's build bot to build a GSI based on.Lineage
https://github.com/AndyCGYan/lineage_build_unified

For building pure AOSP you can use this howto. But it's more complicated.
https://github.com/phhusson/treble_experimentations

We, the TrebleDroid devs, publishing all needed patches here
https://github.com/TrebleDroid

Good luck.
Feel free to join the treble builders group https://t.me/phhtreblebuilders

Harvey

**Comment by ChromiumOS-Guy** [comment]
thanks I'm going to do it after I finish fighting with customs over my package because apparently customs don't appreciate a private person ordering parts in the hundreds

**Comment by LeOS-GSI** [comment]
LoL, yeah, customs are getting more and more worst. Welcome to One World :(

**Comment by ChromiumOS-Guy** [comment]
yeah, I'm probably going to end up releasing independently in front of the Chamber of Commerce
